### PR TITLE
Improve method.isConst() checks

### PR DESCRIPTION
**Pull request by translatenix**
For details see the commit messages.

### CODE REVIEW

**Review by bioball — APPROVED** [review]
Good catch! This is definitely an improvement.

**Comment by translatenix** [comment]
Rebased on main and squashed your changes. Ready from my side.

**Comment by bioball** [comment]
@translatenix did you intend on having this be rebase-merged (as opposed to squash and merge)?

**Comment by translatenix** [comment]
@bioball Yes, I think it's easier to have separate commit messages here.

**Pull request merged**
