### PR TITLE
Convert CODE_OF_CONDUCT to Markdown

### LINKED ISSUE #407: CODE_OF_CONDUCT.adoc not recognized by GitHub
According to `Insights->Community Standards`, this project doesn't have a code of conduct.

Possible solutions:
1. Change `CODE_OF_CONDUCT.adoc` to `CODE_OF_CONDUCT.md`
2. Add `.github/CODE_OF_CONDUCT.md`
3. Define a default code of conduct for Apple projects by adding `CODE_OF_CONDUCT.md` to the `.github` project of the `apple` organization

### PR DESCRIPTION
**Pull request by StefMa**
fixes #407

### CODE REVIEW

**Comment by translatenix** [comment]
You'll need to adapt the syntax for heading and links.

**Comment by StefMa** [comment]
@translatenix fixed 🚀 
Thanks for the hint!

**Comment by translatenix** [comment]
LGTM

**Review by bioball — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
