### PR TITLE
Delete stale files in LanguageSnippetTests/output

### PR DESCRIPTION
**Pull request by translatenix**
When I delete pkl-core/src/test/files/LanguageSnippetTests/output and run "gw test", most output files are regenerated, but 46 of them aren't. I assume these are stale files that should be deleted.

### CODE REVIEW

**Comment by holzensp** [comment]
Your reasoning is sound, but your conclusion is a leap... I'm thinking this is signal some of our tests aren't being executed as expected. This requires a little more deep-diving.

**Comment by translatenix** [comment]
It seems that for every stale output file there's a similarly named generated output file. For example `jsonRenderer1/2/3/6.json.pcf` (stale) vs. `jsonRenderer1/2/3/6.json` (generated).

**Comment by translatenix** [comment]
Another observation is that out of 46 stale output files, 44 have the extension `.pcf`.

**Review by bioball — APPROVED** [review]
This is correct; these are indeed stale expected output files that were never cleaned up.

**Pull request merged**
