### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by translatenix**
- Update dependencies without bumping versions in libs.versions.toml.
- Freeze kotlinx.html and kotlinx.serialization versions until Kotlin itself is updated.

Most version changes affect test dependencies.

### CODE REVIEW

**Comment by holzensp** [comment]
The Graal23 patch file needed updating. Did a `git rebase-patch` and resolved the conflicts. It's not all there yet, because running `git apply --reject patches/graalVm23.patch && gw :pkl-config-java:shadowJar` fails for me on a `Unsupported class file major version 64`, so there's some Java 21 creeping into the build.

**Comment by translatenix** [comment]
> so there's some Java 21 creeping into the build

That’s because some of the Graal JARs are multi-release JARs, i.e., they contain classes for multiple JDK versions (17-21) and the JVM picks the right ones at runtime. However, the shadowJar plugin needs to be able to process all of them. The solution is to update the shadowJar plugin. I did this in my JDK 21 PR, which also got stuck on the patch file.

**Comment by translatenix** [comment]
I updated the shadowJar plugin, which should take care of the "unsupported class file version" problem. The patch still applies cleanly. I can't test the patch because it doesn't work on Linux x64. Can the team trigger another PR build?

**Comment by translatenix** [comment]
Ready to squash and merge from my side.

**Comment by translatenix** [comment]
Further dependency updates and JDK21/22 CI builds are blocked on this.

**Review by bioball — APPROVED** [review]
LGTM, thank you!

**Comment by translatenix** [comment]
@bioball Some CI builds are failing. I believe jline should be locked to its previous version (3.23.0) in `libs.versions.toml` because newer versions have a problem with native image. I already filed an issue for jline.

**Comment by bioball** [comment]
Yeah, sounds good. Where is the issue that you filed? They're using an option that got introduced for GraalVM for JDK 21: https://www.graalvm.org/release-notes/JDK_21/

**Comment by translatenix** [comment]
just sent a PR with a link to my jline PR

**Pull request merged**
